apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-summary
  namespace: tfm
  labels:
    app: product-summary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-summary
  template:
    metadata:
      labels:
        app: product-summary
    spec:
      containers:
        - name: product-summary
          image: acrtfmp4fr3zszvo2xi.azurecr.io/tfm/product-summary:1.0
          imagePullPolicy: Always
      imagePullSecrets:
        - name: az-registry-creds