apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhY3J0Zm1wNGZyM3pzenZvMnhpLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJhY3J0Zm1wNGZyM3pzenZvMnhpIiwicGFzc3dvcmQiOiJmYTFKM2EvWFB3S1BxdU43bmkvMHpiS0gyMS8rM1ZPVFA2aUJtMmFkL2QrQUNSRDJlYWlhIiwiYXV0aCI6IllXTnlkR1p0Y0RSbWNqTjZjM3AyYnpKNGFUcG1ZVEZLTTJFdldGQjNTMUJ4ZFU0M2Jta3ZNSHBpUzBneU1TOHJNMVpQVkZBMmFVSnRNbUZrTDJRclFVTlNSREpsWVdsaCJ9fX0=     
metadata:
  name: az-registry-creds
  namespace: tfm
